name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy production containers
        run: |
          docker-compose -f docker-compose.yml up -d
